### ISSUE TITLE
TO-DO list of webpack issues that need to be resolved 

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-dev-webpack#23]
- [x] [Android] Execution failed for task ':processF0DebugResources' https://github.com/NativeScript/nativescript-dev-webpack/issues/18
- [ ] npm linked modules sometimes get resolved incorrectly https://github.com/NativeScript/nativescript-dev-webpack/issues/15
- [ ] Publish a `__extends` scrubbing loader https://github.com/NativeScript/nativescript-dev-webpack/issues/14
- [x] Clean up device app folder on bundle https://github.com/NativeScript/nativescript-dev-webpack/issues/13
- [x] WebPack'd bundle.js file can't seem to figure out how to load the main /app.component.html https://github.com/NativeScript/nativescript-dev-webpack/issues/10
- [ ] ~~tns debuig ios --bundle --emulator --debug-brk crashes the debugger https://github.com/NativeScript/nativescript-dev-webpack/issues/9~~
- [x] Bundler causes serious weird/crashing issues with ios ng apps with several plugins.  https://github.com/NativeScript/nativescript-dev-webpack/issues/8
- [x] Navigatable page modules must be manually registered with webpack https://github.com/NativeScript/nativescript-dev-webpack/issues/6
- [x] CLI removes tns_modules in platforms https://github.com/NativeScript/nativescript-dev-webpack/issues/5
- [x] Support webpack 2.0 https://github.com/NativeScript/nativescript-dev-webpack/issues/22
- [x] iOS: fonts must be registered manually using (or else bundling will crash app):
```
var font = require("ui/styling/font");
font.ios.registerFont('RobotoRegular.ttf');
```
- [ ] Using `nativescript-telerik-ui` plugin causes issue with bundling if using `RadListView`. `listview.ios.js` must be manually renamed to `listview.js` in `node_modules` :(

**Comment by jlooper** [comment]
@valentinstoychev since webpack is on our radar screen to be be enabled on production builds, I think it's important to note the blockers we have encountered when using it. We can ping Sean Larkin for help :). Thanks for this, Nathan and Nathanael!

**Comment by valentinstoychev** [comment]
Thanks Nathan and Nathanael! Yes - we are planning to enable webpack by default in 2.5.

**Comment by hypery2k** [comment]
any timeline for these issues? In the released docs webpack is mentioned, but with AoT it doesn't work for our app on tns@2.4.0

**Comment by hdeshev** [comment]
I just published support for iOS fonts. Most of the issues on the list are fixed now. Closing this issue.
