### ISSUE TITLE
[Tracking] Webpack 4

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-dev-webpack#492]
- [ ] Webpack recompile fails when using AoT with watch mode.
- [ ] Implement platform matching virtualFs host and provide it to the AngularCompilerPlugin. Example: https://github.com/sis0k0/web-mobile-project/blob/master/webpack.config.js#L256
- [x] Document the changes.
- [x] Update verify-ns-build and CLI tests with the new chunks names and sizes.
- [x] Add the Angular compiler to the vendor chunk when building in JiT mode https://github.com/NativeScript/nativescript-dev-webpack/issues/498
- [x] Require modules dynamically when generating snapshot https://github.com/NativeScript/nativescript-dev-webpack/issues/511
- [x] Enable `compress` option for Android.
- [x] Target esm modules when building with webpack.
- [x] Make the `uglify` flag also enable `production` mode.

**Comment by sis0k0** [comment]
Released with 0.12.0.
